name: CI on macOS

on:
  push:
    branches:
      # Push events to branches matching refs/heads/main
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.16.9
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-14
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc12"
            compiler: "gcc-12"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc11"
            compiler: "gcc-11"
            build_type: Release
            cxx_flags: "-std=c++20"
    steps:
      - name: Set repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPOSITORY_NAME }}
          fetch-depth: 2
          submodules: recursive

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install CMake
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/install_via_brew.sh ccache

      - name: Install compiler ${{ matrix.compiler }}
        env:
          CC: ${{ matrix.compiler }}
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/install_via_brew.sh $(echo ${CC/clang/llvm} | awk -F '-' '{print $1, $2}')

      - name: Load ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.compiler }} --version

      - name: Configure tests
        env:
          COMPILER: ${{ matrix.compiler }}
        run: |
          mkdir build
          cd build
          cmake ../${{ env.REPOSITORY_NAME }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                              -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"
          make -j3 gtest_build

      - name: Build application
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 75M
        run: |
          ccache -z
          cd build
          make -k -j3
          ccache -sv

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 12
          CCACHE_MAXSIZE: 75M
        run: |
          ccache -z
          cd build
          make -k -j3 api_test cli_test
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
